project:
  type: website
  output-dir: docs

website:
  title: "Oscar Oelrich"
  navbar:
    search: true
    left:
      - text: "About"
        file: index.qmd
      - publications.qmd
      - blog.qmd

format:
  html:
    light: flatly
    dark: darkly
    css: styles.css
    toc: true



