project:
  type: website
  output-dir: docs

website:
  title: "Oscar Oelrich"
  site-url: https://ooelrich.github.io/me/
  description: "Gaussian terrors"
  navbar:
    search: true
    left:
      - text: "About"
        file: index.qmd
      - publications.qmd
      - blog.qmd
    right:
      - icon: rss
        href: blog.qmd

format:
  html:
    light: flatly
    dark: darkly
    css: styles.css
    toc: true



