project:
  type: website
  output-dir: docs

website:
  title: "Oscar Oelrich"
  navbar:
    search: true
    left:
      - href: index.qmd
      - href: publications.qmd
      - href: blog.qmd
      - href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



