project:
  type: website
  output-dir: docs

website:
  title: "Oscar Oelrich"
  navbar:
    left:
      - href: about.qmd
      - href: publications.qmd
      - href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



