---
title: "Publications"
---

# Peer-reviewed


Oscar Oelrich, Mattias Villani, Sebastian Ankargren. 2024. ”Local prediction pools.” Journal of Forecasting 43(1): 103–107. [Open access](https://onlinelibrary.wiley.com/doi/10.1002/for.3030).


# Pre-prints


Oscar Oelrich, Shutong Ding, Måns Magnusson, Aki Vehtari, Mattias Villani. ”When are Bayesian model probabilities overconfident?” <https://arxiv.org/abs/2003.04026>

Oscar Oelrich, Mattias Villani. "Joint estimation of the predictive ability of experts using a multi-output Gaussian process." <https://arxiv.org/abs/2402.07439>

Oscar Oelrich, Mattias Villani. "Modeling local predictive ability using power-transformed Gaussian processes." <https://arxiv.org/abs/2402.02068>

# Other

Oscar Oelrich (2022). Learning local predictive accuracy for expert evaluation and forecast combination. Dissertation for the degree of Doctor of Philosophy in Statistics, Stockholm University. The kappa can be found [here](http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1708601&dswid=-4706).

Oscar Oelrich (2014). Causal Inference Using Propensity Score Matching in Clustered Data. Master's thesis, Uppsala University. The full text can be found [here](https://uu.diva-portal.org/smash/record.jsf?dswid=5279&pid=diva2%3A723279&c=2&searchType=SIMPLE&language=en&query=oscar+oelrich&af=%5B%5D&aq=%5B%5B%5D%5D&aq2=%5B%5B%5D%5D&aqe=%5B%5D&noOfRows=50&sortOrder=author_sort_asc&sortOrder2=title_sort_asc&onlyFullText=false&sf=all).